maxWeight: 20
maxDimension: 24

inboundShipping: 0
extraFees: 1

amazonPriceDifference: 7

logging: false
debug: false
feeLogging: false

roiMarkers:
  - .25
  - .35
  - .5
  - .6
  - 75
  - 1

rankMarkers:
  - 10
  - 5
  - 3
  - 1

buyPointThreshold: 5

inboundShippingPerPound: .50

maxLargeStandardWeight: 20
maxLargeStandardDimensions:
       - 18
       - 14
       - 8

maxSmallStandardMediaWeight: 0.875
maxSmallStandardNonMediaWeight: .75
maxSmallStandardDimensions:
  - 15
  - 12
  - .75

maxSmallOversizeWeight: 70
maxSmallOversizeDimensions:
  - 60
  - 30
