maxWeight: 20
maxDimension: 24

inboundShipping: 0

amazonPriceDifference: 7

logging: true
debug: false
feeLogging: false

roiMarkers:
  - .5
  - .6
  - .7
  - .85
  - 1
  - 2

rankMarkers:
  - 5
  - 3
  - 1
  - .5

buyPointThreshold: 5

inboundShippingPerPound: .50

maxLargeStandardWeight: 20
maxLargeStandardDimensions:
       - 18
       - 14
       - 8

maxSmallStandardMediaWeight: 0.875
maxSmallStandardNonMediaWeight: .75
maxSmallStandardDimensions:
  - 15
  - 12
  - .75

maxSmallOversizeWeight: 70
maxSmallOversizeDimensions:
  - 60
  - 30
